version: 1.0.{build}

environment:
  matrix:
  - Python: 35-x64

build_script:
  - PATH %CD%\here\bin;C:\mingw\bin;C:\python%Python%;C:\python%Python%\scripts;%PATH%
  - pip install pyflakes pycodestyle coverage coveralls nose

test_script:
  - pyflakes .
  - pycodestyle .
  - nosetests
  - coverage report
  - if not "%COVERALLS_REPO_TOKEN%"=="" coveralls
